### ISSUE TITLE
Usage Example?

### ISSUE THREAD

**Issue by USMortality** [cyianor/ithmbrdr#2]
Could you help me figure out how to extract jpg's with this tool from e.g.: `F1015_1.ithmb`? Thanks

**Comment by cyianor** [comment]
Hi!

This tool only extracts PNG files, but once you have those it should be easy to convert to JPEG.

See the new usage example in the README file. Note that I changed to the `flag` package for command line handling and made the ID an optional argument `-id`. You will have to pull the current code to use it that way.
